# Generated by Django 3.0.7 on 2021-08-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('ANNOUNCEMENTS', 'announcements'), ('COMMENTARY', 'commentary'), ('HIGHLIGHTS', 'highlights'), ('GUIDES', 'guides'), ('PLAYER', 'player'), ('FEATURES', 'features'), ('MATCH FEATURES', 'match features')], max_length=255, null=True)),
                ('format', models.CharField(blank=True, choices=[('VIDEO', 'video'), ('ARTICLE', 'article')], max_length=255, null=True)),
                ('events', models.CharField(blank=True, choices=[('SPRING', 'spring'), ('SUMMER', 'summer'), ('INTERNATIONAL', 'international'), ('ACADEMY', 'academy')], max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('video_link', models.TextField(blank=True, null=True)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('google_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
