# Generated by Django 3.0.7 on 2021-08-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210803_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='format',
            new_name='formats',
        ),
    ]
